# Generated by Django 5.0.3 on 2026-07-21 11:19

import apps.cohorts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Une classe archivée n'accepte plus de nouveaux membres.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Formateur responsable. Une classe orpheline reste gérable par un admin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "db_table": "cohorts_cohort",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CohortInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.cohorts.models.generate_invite_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="LEARNER",
                        help_text="Rôle attribué à l'arrivée. TRAINER n'est émissible que par un admin.",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.cohorts.models.default_invite_expiry
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vide = illimité. Utile pour un lien nominatif.",
                        null=True,
                    ),
                ),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("is_revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide pour une invitation de formateur (réservée aux admins).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="cohorts.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien d'invitation",
                "verbose_name_plural": "Liens d'invitation",
                "db_table": "cohorts_invite",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["trainer", "is_active"], name="cohorts_coh_trainer_d6d3b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cohortinvite",
            index=models.Index(
                fields=["cohort", "is_revoked"], name="cohorts_inv_cohort__bf1835_idx"
            ),
        ),
    ]
