# Generated by Django 5.0.3 on 2026-07-21 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        help_text="Identité de l'auteur au moment de l'action (figée).",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SET_ROLE", "Changement de rôle"),
                            ("SET_ACTIVE", "Activation / désactivation"),
                            ("ANONYMIZE", "Anonymisation (RGPD)"),
                            ("ASSIGN_COHORT", "Rattachement à une classe"),
                            ("UNLOCK_CHAPTER", "Déblocage de chapitre"),
                            ("LOCK_CHAPTER", "Reverrouillage de chapitre"),
                            ("CREATE_COHORT", "Création de classe"),
                            ("ASSIGN_TRAINER", "Affectation de formateur"),
                            ("INVITE_CREATED", "Invitation émise"),
                            ("INVITE_REVOKED", "Invitation révoquée"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Identifiant de l'objet visé (compte, classe, chapitre).",
                        null=True,
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        help_text="Désignation de la cible au moment de l'action (figée). Survit à une anonymisation, c'est tout son intérêt.",
                        max_length=255,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Avant / après, au format {'before': …, 'after': …}.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auteur de l'action. Nul si le compte a disparu depuis.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée de journal",
                "verbose_name_plural": "Journal d'audit",
                "db_table": "administration_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_audit_created"),
                    models.Index(
                        fields=["action", "-created_at"], name="idx_audit_action"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="idx_audit_actor"
                    ),
                ],
            },
        ),
    ]
