# Generated by Django 5.0.3 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SET_ROLE", "Changement de rôle"),
                    ("SET_ACTIVE", "Activation / désactivation"),
                    ("ANONYMIZE", "Anonymisation (RGPD)"),
                    ("ACCOUNT_DELETED", "Suppression de compte (self-service RGPD)"),
                    ("ASSIGN_COHORT", "Rattachement à une classe"),
                    ("UNLOCK_CHAPTER", "Déblocage de chapitre"),
                    ("LOCK_CHAPTER", "Reverrouillage de chapitre"),
                    ("CREATE_COHORT", "Création de classe"),
                    ("ASSIGN_TRAINER", "Affectation de formateur"),
                    ("INVITE_CREATED", "Invitation émise"),
                    ("INVITE_REVOKED", "Invitation révoquée"),
                ],
                max_length=30,
            ),
        ),
    ]
