# Generated by Django 5.0.3 on 2026-07-21 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_unique_user_email_ci"),
        ("cohorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="cohorts.cohort",
            ),
        ),
    ]
