# Generated by Django 5.0.3 on 2026-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'exercice du droit à l'effacement (RGPD).",
                null=True,
            ),
        ),
    ]
