# Generated by Django 5.0.3 on 2026-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_anonymized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_key",
            field=models.CharField(
                blank=True,
                help_text="Clé du catalogue (« motif-palette »). Vide = initiales.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("AUTO", "Selon le système"),
                    ("LIGHT", "Clair"),
                    ("DARK", "Sombre"),
                ],
                default="AUTO",
                help_text="Préférence d'affichage, rattachée au compte plutôt qu'au navigateur : elle suit l'apprenant d'un poste à l'autre.",
                max_length=10,
            ),
        ),
    ]
