# Generated by Django 5.0.3 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_avatar_key_profile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'acceptation de la politique de confidentialité et des CGU à l'inscription. Preuve du consentement (RGPD).",
                null=True,
            ),
        ),
    ]
