# Generated by Django 5.0.3 on 2026-07-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_terms_accepted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
