# Generated by Django 5.2.11 on 2026-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_avatar_catalogue_visages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar_key",
            field=models.CharField(
                blank=True,
                help_text="Clé du catalogue (« visage-palette »). Vide = initiales.",
                max_length=40,
            ),
        ),
    ]
