# Generated by Django 5.2.11 on 2026-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profile_avatar_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_in_leaderboard",
            field=models.BooleanField(
                default=True,
                help_text="Décoché, le compte n'apparaît plus dans le classement (sa progression et ses points sont conservés).",
            ),
        ),
    ]
