# Generated by Django 5.2.11 on 2026-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_show_in_leaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_border",
            field=models.CharField(
                blank=True,
                help_text="Bordure de la vignette. Vide = aucune.",
                max_length=20,
            ),
        ),
    ]
