# Generated by Django 5.0.3 on 2025-12-12 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("order_index", models.IntegerField(db_index=True, default=0)),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Estimated duration in minutes"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "db_table": "courses_chapter",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("THEORY", "Théorie"),
                            ("EXERCISE", "Exercice"),
                            ("QUIZ", "Quiz"),
                        ],
                        default="THEORY",
                        max_length=20,
                    ),
                ),
                ("order_index", models.IntegerField(db_index=True, default=0)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Markdown content for theory lessons"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=10, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=10, help_text="Points awarded for completion"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "db_table": "courses_lesson",
                "ordering": ["chapter__order_index", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Exercise instructions in Markdown"),
                ),
                ("starter_code", models.TextField(help_text="Initial code template")),
                (
                    "solution",
                    models.TextField(
                        help_text="Reference solution (hidden from students)"
                    ),
                ),
                (
                    "tests",
                    models.JSONField(
                        default=list,
                        help_text="List of test cases with name, code, and points",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Facile"),
                            ("MEDIUM", "Moyen"),
                            ("HARD", "Difficile"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=0, help_text="0 = unlimited"),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=300,
                        help_text="Time limit in seconds for code execution",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of hints (progressive help)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "db_table": "courses_exercise",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(help_text="Project requirements in Markdown"),
                ),
                (
                    "starter_files",
                    models.JSONField(
                        blank=True, default=dict, help_text="Starter files structure"
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        default=list,
                        help_text="List of evaluation criteria with points",
                    ),
                ),
                (
                    "deadline_days",
                    models.IntegerField(
                        default=7, help_text="Days allowed to complete"
                    ),
                ),
                ("points", models.IntegerField(default=100)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="courses.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "courses_project",
                "ordering": ["chapter__order_index"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="Quiz instructions"),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="List of questions with type, text, options, correct_answer, points",
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70, help_text="Minimum percentage to pass"
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=0, help_text="Time limit in minutes, 0 = unlimited"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=3, help_text="0 = unlimited"),
                ),
                ("randomize_questions", models.BooleanField(default=False)),
                ("randomize_options", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "db_table": "courses_quiz",
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["chapter", "order_index"], name="courses_les_chapter_928e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["lesson_type"], name="courses_les_lesson__299384_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("chapter", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("chapter", "slug")},
        ),
    ]
