# Generated by Django 5.0.3 on 2026-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="language",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("javascript", "JavaScript"),
                ],
                default="html",
                max_length=20,
            ),
        ),
    ]
