# Generated by Django 5.0.3 on 2026-07-21 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Identifiant stable utilisé par le code et le grand livre de points",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(
                        help_text="Texte révélé une fois le badge obtenu",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏅", help_text="Emoji du badge", max_length=8
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRESSION", "Progression"),
                            ("MASTERY", "Maîtrise"),
                            ("REGULARITY", "Régularité"),
                            ("EXPLORATION", "Exploration"),
                        ],
                        default="PROGRESSION",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Argent"),
                            ("GOLD", "Or"),
                            ("LEGENDARY", "Légendaire"),
                        ],
                        default="BRONZE",
                        max_length=20,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("LESSONS_COMPLETED", "Leçons complétées"),
                            ("CHAPTERS_COMPLETED", "Chapitres terminés"),
                            ("CHAPTER_MASTERED", "Chapitre précis terminé"),
                            ("EXERCISES_PASSED", "Exercices réussis"),
                            ("QUIZZES_PASSED", "Quiz réussis"),
                            ("PERFECT_QUIZZES", "Quiz sans faute (100%)"),
                            ("FIRST_TRY_QUIZZES", "Quiz réussis du premier coup"),
                            ("PERSEVERANCE", "Réussite après N tentatives"),
                            ("POINTS_TOTAL", "Total de points atteint"),
                            ("STREAK_DAYS", "Jours consécutifs"),
                            ("TIME_SPENT", "Temps d'apprentissage cumulé"),
                            ("FAST_LESSONS", "Leçons bouclées rapidement"),
                            ("NIGHT_OWL", "Activités nocturnes"),
                            ("EARLY_BIRD", "Activités matinales"),
                            ("WEEKEND_LEARNER", "Activités le week-end"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Paramètres de la règle, ex: {"count": 5}',
                    ),
                ),
                (
                    "points_reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Points crédités une seule fois, à la première obtention",
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="Masqué (nom, description, critère) tant qu'il n'est pas obtenu",
                    ),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True,
                        help_text="Énigme affichée à la place de la description quand le badge est secret",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "gamification_badge",
                "ordering": ["order_index", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order_index"],
                        name="gamificatio_is_acti_0fe28a_idx",
                    ),
                    models.Index(
                        fields=["category"], name="gamificatio_categor_16b812_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_seen",
                    models.BooleanField(
                        default=False,
                        help_text="Passe à True une fois l'animation de révélation affichée",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valeur du compteur au moment du déclenchement (traçabilité)",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge obtenu",
                "verbose_name_plural": "Badges obtenus",
                "db_table": "gamification_user_badge",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Série",
                "verbose_name_plural": "Séries",
                "db_table": "gamification_user_streak",
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Peut être négatif pour un ajustement"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("LESSON_COMPLETED", "Leçon terminée"),
                            ("QUIZ_PASSED", "Quiz réussi"),
                            ("EXERCISE_PASSED", "Exercice réussi"),
                            ("BADGE_EARNED", "Badge obtenu"),
                            ("LEGACY", "Report de solde antérieur"),
                            ("MANUAL", "Ajustement manuel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        help_text="Clé d'idempotence, ex: lesson:<uuid> ou badge:<code>",
                        max_length=120,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de points",
                "verbose_name_plural": "Transactions de points",
                "db_table": "gamification_point_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gamificatio_user_id_1e1e38_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="gamificatio_reason_a151cf_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pointtransaction",
            constraint=models.UniqueConstraint(
                fields=("user", "source_key"), name="unique_point_source_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["user", "-earned_at"], name="gamificatio_user_id_1eb32b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["user", "is_seen"], name="gamificatio_user_id_0b00ae_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_badge_per_user"
            ),
        ),
    ]
