# Generated by Django 5.0.3 on 2025-12-13 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LESSON_STARTED", "Lesson Started"),
                            ("LESSON_COMPLETED", "Lesson Completed"),
                            ("EXERCISE_SUBMITTED", "Exercise Submitted"),
                            ("QUIZ_COMPLETED", "Quiz Completed"),
                            ("CHAPTER_UNLOCKED", "Chapter Unlocked"),
                            ("BADGE_EARNED", "Badge Earned"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (score, time, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="courses.chapter",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="courses.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "progression_activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="progression_user_id_fd0b81_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="progression_activit_4e42b1_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="progression_created_39fb60_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChapterAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_unlocked", models.BooleanField(default=False)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="courses.chapter",
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Trainer qui a débloqué ce chapitre",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocked_chapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter Access",
                "verbose_name_plural": "Chapter Accesses",
                "db_table": "progression_chapter_access",
                "ordering": ["chapter__order_index"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_unlocked"],
                        name="progression_user_id_88f199_idx",
                    ),
                    models.Index(
                        fields=["chapter"], name="progression_chapter_2bf7e9_idx"
                    ),
                ],
                "unique_together": {("user", "chapter")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("last_code", models.TextField(blank=True, default="")),
                ("attempts", models.IntegerField(default=0)),
                ("is_passed", models.BooleanField(default=False)),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Score sur 100", null=True
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(default=0, help_text="Time spent in seconds"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="courses.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress",
                "db_table": "progression_user_progress",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="progression_user_id_7689ff_idx"
                    ),
                    models.Index(
                        fields=["lesson"], name="progression_lesson__413865_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="progression_updated_02bf07_idx"
                    ),
                ],
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
