# Generated by Django 5.0.3 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="points_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="quiz_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
